FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-devel
WORKDIR /code
COPY ./finetuning/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./finetuning /code/finetuning
CMD ["python", "finetuning/main.py"]
